### PR TITLE
fix "cannot use myByte (type int) as type byte in array or slice literal"

### PR DESCRIPTION
**Pull request by acidobinario**
and added some explanation of what's going on in there :)

### CODE REVIEW

**Comment by svarlamov** [comment]
Thank you for this fix and extra explanation! I'm wondering however if casting to `byte` is the best way though... What do you think of changing the definition to `var myByte byte = 65`? This would obviate the need for the cast which complicates the code for beginners IMHO

**Comment by acidobinario** [comment]
yes, it looks kinda confusing casting the value multiple times, i would say that leaving it as `var myByte byte` it's good enough

**Comment by acidobinario** [comment]
now it looks cleaner because the comment was talking about using a byte (0-255) :D

**Comment by svarlamov** [comment]
Perfect, thanks! Merging now 😄

**Pull request merged**
